---
ops: [evaluate]
model: {
    path: ./deeperdeepsea.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1024,
        n_targets: 9,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.MultiSampler {
    train_sampler: !obj:selene_sdk.samplers.dataloader.SamplerDataLoader {
        sampler: !obj:selene_sdk.samplers.RandomPositionsSampler {
            target_path: ../MACS2_data/all_sorted.bed.gz,
            reference_sequence: !obj:selene_sdk.sequences.Genome {
                input_path: ../resources/hg38_UCSC.fa,
                blacklist_regions: hg38
            },
            features: !obj:selene_sdk.utils.load_features_list {
                input_path: ../MACS2_data/features.txt
            },
            test_holdout: [chr8, chr9],
            validation_holdout: [chr10],
            sequence_length: 1024,
            center_bin_to_predict: [512, 513],
            feature_thresholds: null,
            save_datasets: []
        },
        num_workers: 16,
        batch_size: 64,
    },
    validate_sampler: !obj:selene_sdk.samplers.RandomPositionsSampler {
        target_path: ../MACS2_data/all_sorted.bed.gz,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: ../resources/hg38_UCSC.fa,
            blacklist_regions: hg38
        },
        features: !obj:selene_sdk.utils.load_features_list {
            input_path: ../MACS2_data/features.txt
        },
        test_holdout: [chr8, chr9],
        validation_holdout: [chr10],
        sequence_length: 1024,
        center_bin_to_predict: [512, 513],
        mode: validate,
        save_datasets: [validate, test],
        output_dir: ../saved_evaluation_data
    },
    test_sampler: !obj:selene_sdk.samplers.RandomPositionsSampler {
        target_path: ../MACS2_data/all_sorted.bed.gz,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: ../resources/hg38_UCSC.fa,
            blacklist_regions: hg38
        },
        features: !obj:selene_sdk.utils.load_features_list {
            input_path: ../MACS2_data/features.txt
        },
        test_holdout: [chr8, chr9],
        validation_holdout: [chr10],
        sequence_length: 1024,
        center_bin_to_predict: [512, 513],
        mode: test,
        save_datasets: [test],
        output_dir: ../saved_evaluation_data
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path:  ./data/features.txt
    }
}
evaluate_model: !obj:selene_sdk.EvaluateModel {
    batch_size: 64,
    n_test_samples: 120000,
    use_cuda: True,  # TODO: update this if CUDA is not on your machine
    data_parallel: True,
    trained_model_path: models/2022-05-02-21-13-25/best_model.pth.tar,
    features: !obj:selene_sdk.utils.load_features_list {
        input_path:  ../MACS2_data/features.txt
    },
    metrics: {
        roc_auc: !import sklearn.metrics.roc_auc_score,
        average_precision: !import sklearn.metrics.average_precision_score
    }
}

output_dir: ./models
random_seed: 1447
...
